# SSY098
## Project 3: Structure-from-Motion in 2D

In this project, you will implement a Structure-from-Motion pipeline in 2D, which is equivalent
to stitching together multiple 2D images of a planar surface.

### AI Usage Statement
<!-- Claude (claude-sonnet-4-6 via Claude Code) was used as an assistant during the completion of this lab. The AI was not used to directly write or generate implementation code, but was consulted for conceptual explanations and debugging guidance throughout the assignment.                          
                       
Specifically, the AI was used to:
  - Explain inverse warping and why target pixel locations are always known independently of the warp
  - Explain affine transformation estimation using np.linalg.lstsq, including why the point matrix must be augmented with ones to solve for translation simultaneously with the linear part        
  - Clarify NumPy concepts such as np.squeeze vs slicing for removing array elements, axis parameter behavior in np.sum, boolean array indexing with ~, and .sum() on boolean arrays                   
  - Debug a cv.warpPerspective dtype error requiring float64 transformation matrices                 
  - Debug an incorrect transformation matrix construction using np.ones instead of np.zeros, causing a corrupted perspective warp
  - Debug a cv.drawMatchesKnn argument error caused by passing coordinate arrays instead of cv.KeyPoint objects
  - Explain RANSAC, including the role of the minimal solver
  - Explain histogram equalization and its role in making SIFT features more comparable across images with different contrast distributions
  - Explain deformable B-spline registration, shrink factors and the coarse-to-fine multi-resolution scheme
                                                                                                     
All implementations were written by me, with the AI serving as an explanatory resource and assistant during debugging. -->

 ## Imports
 

In [68]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
import pandas as pd
from typing import Tuple, List, Sequence, Union, Optional
import glob

## Loading Dataset
This section loads the dataset used in this project

In [69]:
bark_paths = sorted(glob.glob('data/bark/*.ppm'))
boat_paths = sorted(glob.glob('data/boat/*.ppm'))
graf_paths = sorted(glob.glob('data/graf/*.ppm'))
wall_paths = sorted(glob.glob('data/wall/*.ppm'))

bark_images = [cv.imread(p, cv.IMREAD_COLOR_RGB) for p in bark_paths]
boat_images = [cv.imread(p, cv.IMREAD_COLOR_RGB) for p in boat_paths]
graf_images = [cv.imread(p, cv.IMREAD_COLOR_RGB) for p in graf_paths]
wall_images = [cv.imread(p, cv.IMREAD_COLOR_RGB) for p in wall_paths]
bark_images_gray = [cv.cvtColor(img, cv.COLOR_RGB2GRAY) for img in bark_images]
boat_images_gray = [cv.cvtColor(img, cv.COLOR_RGB2GRAY) for img in boat_images]
graf_images_gray = [cv.cvtColor(img, cv.COLOR_RGB2GRAY) for img in graf_images]
wall_images_gray = [cv.cvtColor(img, cv.COLOR_RGB2GRAY) for img in wall_images]

## Homography Estimation With RANSAC

The following section defines the code required to estimate the homography transform between point correspondences from two different images.
The pipeline requires only that the point correspondences are provided as pixel coordinates of equal number. The result is the estimated homography $H$

In [70]:
def similarity_transform(pts: np.ndarray):
    """
    Compute similarity transform T and transform points
    
    Args:
    - pts (np.ndarray): Points to transform, shape (2, N)

    Returns:
    - pts_prime (np.ndarray): Homogoneous points with transform T applied
    - T (np.ndarray): Similarity Transform T such that pts_prime = T @ pts
    """
    mu = np.mean(pts)
    avg_norm = np.sum(np.linalg.norm(pts, axis=0)) / pts.shape[1]
    s = np.sqrt(2) / avg_norm

    translation = np.diag(np.ones(3))
    translation[0][2] = -mu
    translation[1][2] = -mu

    scale = np.diag(np.ones(3))
    scale[0][0] = s
    scale[1][1] = s

    T = scale @ translation
    pts_hom = np.vstack([pts, np.ones(pts.shape[1])])
    pts_prime = T @ pts_hom
    pts_prime = pts_prime / pts_prime[2]

    return pts_prime, T

In [71]:
# Sanity check similarity_transform
# Test similarity_transform: two points (0,0) and (4,4)
# mu=2, avg_norm=2*sqrt(2), s=0.5 -> expected T = [[0.5,0,-1],[0,0.5,-1],[0,0,1]]
# Transformed points: (-1,-1) and (1,1)
pts_test = np.array([[0., 4.], [0., 4.]])
pts_prime_test, T_test = similarity_transform(pts_test)
pts_hom_test = np.vstack([pts_test, np.ones(pts_test.shape[1])])

# 1. Consistency
np.testing.assert_allclose(pts_prime_test, T_test @ pts_hom_test, atol=1e-10)

# 2. Centroid at origin
np.testing.assert_allclose(pts_prime_test[:2].mean(axis=1), [0., 0.], atol=1e-10)

# 3. Average norm == sqrt(2)
np.testing.assert_allclose(
  np.mean(np.linalg.norm(pts_prime_test[:2], axis=0)), np.sqrt(2), atol=1e-10)

print("All checks passed.")

All checks passed.


In [72]:
def dlt_estimate_homography(pts: np.ndarray, pts_prime: np.ndarray):
    """
    Estimate the Homography H using DLT

    Args:
    - pts (np.ndarray): Normalized original homogeneous points, shape (3, 4)
    - pts_prime (np.ndarray): Normalized transformed homogeneous points, shape (3, 4)
    
    Returns:
    - H (np.ndarray): The estimated homography
    """

    A = np.zeros((8,9))
    for i in range(4):
        A_i = np.zeros((2,9))
        X = pts[:,i]
        X_prime = pts_prime[:,i]

        A_i[0,3:6] = -X_prime[2] * X
        A_i[0,6:9] = X_prime[1] * X
        A_i[1,0:3] = X_prime[2] * X
        A_i[1,6:9] = -X_prime[0] * X

        A[2*i:2*i+2,:] = A_i

    _, _, Vh = np.linalg.svd(A)
    h = Vh[-1]
    H = np.array([h[0:3], h[3:6], h[6:9]])
    return H
        

In [73]:
# Sanity check dlt_estimate_homography
H_true = np.array([[2., 0., 1.],
                 [0., 3., 2.],
                 [0., 0., 1.]])

# 4 points in homogeneous coords (3, 4)
pts = np.array([[0., 2., 1., 3.],
              [0., 1., 3., 2.],
              [1., 1., 1., 1.]])

# Apply H_true and normalise
pts_prime = H_true @ pts
pts_prime = pts_prime / pts_prime[2]

H_est = dlt_estimate_homography(pts, pts_prime)

# H is defined up to scale. Normalise by H[2,2]
H_true_n = H_true / H_true[2, 2]
H_est_n  = H_est  / H_est[2, 2]

np.testing.assert_allclose(H_est_n, H_true_n, atol=1e-8)
print("DLT test passed.")

DLT test passed.


In [74]:
def residual_sum_of_squares(H: np.ndarray, pts: np.ndarray, pts_prime: np.ndarray) -> np.ndarray:
    """
    Calculate the residual sum of squares between the transformed points and the given points.
    
    Args:
    - H (np.ndarray): Homography transformation matrix, shape (3, 3)
    - pts (np.ndarray): Original points, shape (3, N)
    - pts_prime (np.ndarray): Transformed points, shape (3, N)

    Returns:
    - residual_ss (np.ndarray): Residual sum of squares, shape (N,)
    """
    H_points = H @ pts
    H_points = H_points / H_points[2]
    residuals = pts_prime - H_points
    return np.sum(residuals**2, axis=0)

In [75]:
def ransac_fit_homography(pts: np.ndarray, pts_prime: np.ndarray, thresh: float, n_iter: int = 10000):
    """
    Estimate the affine transformation matrix A and translation vector t
    using RANSAC to handle outliers.
    
    Args:
    - pts (np.ndarray): Original points, shape (2, n)
    - pts_prime (np.ndarray): Transformed points, shape (2, n)
    - thresh (float): Threshold for considering a point as an inlier
    - n_iter (int): Number of iterations for RANSAC

    Returns:
    - best_H_tilde (np.ndarray): The best homography found in RANSAC
    - best_inliers (np.ndarray): The boolean mask of inliers of the best homography
    """
    max_inliers = 0
    best_H_tilde = None
    best_inliers = None
    for _ in range(n_iter):                                           
        idx = np.random.choice(pts.shape[1], 4, replace=False)                                       
        H_tilde = dlt_estimate_homography(pts[:, idx], pts_prime[:, idx])
        rss = residual_sum_of_squares(H_tilde, pts, pts_prime)                      
        inliers = rss < thresh
        
        if inliers.sum() > max_inliers:                                                              
            max_inliers = inliers.sum()
            best_H_tilde = H_tilde
            best_inliers = inliers

    return best_H_tilde, best_inliers

In [76]:
def estimate_homography(pts: np.ndarray, pts_tilde: np.ndarray, thresh: float, n_iter: int = 10000):
    """
    Estimate the Homography H using DLT

    Args:
    - pts (np.ndarray): Original points, shape (2, N)
    - pts_prime (np.ndarray): Transformed homogeneous points, shape (2, N)
    
    Returns:
    - H (np.ndarray): The estimated homography
    - inliers (np.ndarray): The boolean mask of inliers of the estimated homography
    """
    pts, T = similarity_transform(pts)
    pts_tilde, T_tilde = similarity_transform(pts_tilde)

    H_tilde, inliers = ransac_fit_homography(pts, pts_tilde, thresh, n_iter)
    H = np.linalg.inv(T_tilde) @ H_tilde @ T
    return H, inliers

In [77]:
H_true = np.array([[2., 0., 1.],
                 [0., 3., 2.],
                 [0., 0., 1.]])

np.random.seed(42)
n_inliers, n_outliers = 20, 8

# Inlier correspondences derived from H_true
pts_in = np.random.uniform(1, 5, (2, n_inliers))
pts_hom = np.vstack([pts_in, np.ones(n_inliers)])
pts_tilde_hom = H_true @ pts_hom
pts_tilde_in = pts_tilde_hom[:2] / pts_tilde_hom[2]

# Add random outliers
pts       = np.hstack([pts_in,       np.random.uniform(0, 5,  (2, n_outliers))])
pts_tilde = np.hstack([pts_tilde_in, np.random.uniform(0, 20, (2, n_outliers))])

H_est, inliers = estimate_homography(pts, pts_tilde, thresh=0.05, n_iter=1000)

H_true_n = H_true / H_true[2, 2]
H_est_n  = H_est  / H_est[2, 2]
np.testing.assert_allclose(H_est_n, H_true_n, atol=1e-4)
print("True homography:")
print(H_true_n)
print("\nEstimated homography:")
print(H_est_n.round(3))
print("\nRANSAC estimate_homography test passed.")

True homography:
[[2. 0. 1.]
 [0. 3. 2.]
 [0. 0. 1.]]

Estimated homography:
[[2. 0. 1.]
 [0. 3. 2.]
 [0. 0. 1.]]

RANSAC estimate_homography test passed.


## SIFT Feature Matching

The following section defines the methods and functions required to extract point correspondences from two images using SIFT feature matching.

In [78]:
def extract_sift_features(image: np.ndarray) -> Tuple[Sequence[cv.KeyPoint], cv.UMat]:
    """
    Extracts SIFT descriptors from an image.

    Args:
    - image (np.ndarray): The input image.

    Returns:
    - Tuple[Sequence[cv.KeyPoint], cv.UMat]: A tuple containing the keypoints and descriptors.
    """
    
    # Create a SIFT detector
    sift = cv.SIFT.create()

    # Detect keypoints and compute descriptors
    keypoints, descriptors = sift.detectAndCompute(image, None)
    
    return keypoints, descriptors

def match_descriptors(
        descriptors_src: cv.UMat, 
        descriptors_tgt: cv.UMat, 
        max_ratio: float = 0.8) -> Tuple[Sequence[Sequence[cv.DMatch]], Sequence[Sequence[cv.DMatch]]]:
    """
    Matches descriptors from the test image to the training descriptors using brute-force
    matches and Lowe's ratio test.

    Returns the good matches and all matches.

    Args:
    - descriptors_src (cv.UMat): The source image descriptors.
    - descriptors_tgt (cv.UMat): The target image descriptors.
    - max_ratio (float): The maximum ratio for Lowe's ratio test.

    Returns:
    - Tuple[Sequence[Sequence[cv.DMatch]], Sequence[Sequence[cv.DMatch]]]: A tuple containing the good matches and all matches.

    """
    bf = cv.BFMatcher(cv.NORM_L2, crossCheck=False)
    matches = bf.knnMatch(descriptors_src, descriptors_tgt, k=2)

    # Apply Lowe's ratio test
    good_matches = []

    # Iterate through the matches and apply the ratio test
    # selecting only the good matches
    for i, (m,n) in enumerate(matches):
        if m.distance < max_ratio * n.distance:
            good_matches.append([m])

    return good_matches, matches

def extract_keypoint_matches(
        pts_src: Sequence[cv.KeyPoint], 
        pts_tgt: Sequence[cv.KeyPoint], 
        matches: Sequence[Sequence[cv.DMatch]]) -> Tuple[np.ndarray, np.ndarray]:
    """
    Extracts the matched keypoints from the source and target images.

    Args:
    - pts_src (Sequence[cv.KeyPoint]): The keypoints from the source image.
    - pts_tgt (Sequence[cv.KeyPoint]): The keypoints from the target image.
    - matches (Sequence[Sequence[cv.DMatch]]): The matches between the keypoints.

    Returns:
    - Tuple[numpy.ndarray, numpy.ndarray]: A tuple containing the matched keypoints from the source and target images.
    """
    
    pts_src_to_use = [pts_src[m[0].queryIdx].pt for m in matches]
    pts_tgt_to_use = [pts_tgt[m[0].trainIdx].pt for m in matches]
    pts_src_to_use = np.array(pts_src_to_use).astype(np.float32).T
    pts_tgt_to_use = np.array(pts_tgt_to_use).astype(np.float32).T

    return pts_src_to_use, pts_tgt_to_use


def plot_matches(
        source: np.ndarray,
        target: np.ndarray, 
        pts_src: Sequence[cv.KeyPoint], 
        pts_tgt: Sequence[cv.KeyPoint], 
        matches: Sequence[Sequence[cv.DMatch]], 
        max_ratio: float = 0.8,
        ) -> Tuple[plt.Figure, plt.Axes]:
    """
    Plots the matches between two images.
    
    Args:
    - source np.ndarray: The source image.
    - target np.ndarray: The target image.
    - pts_src (Sequence[cv.KeyPoint]): Keypoints from the source image.
    - pts_tgt (Sequence[cv.KeyPoint]): Keypoints from the target image.
    - matches (Sequence[Sequence[cv.DMatch]]): All matches between the keypoints.
    - max_ratio (float): The maximum ratio for Lowe's ratio test.

    Returns:
    - Tuple[plt.Figure, plt.Axes]: A tuple containing the figure and axes of the plot.
    
    """

    match_mask = [[0, 0] for i in range(len(matches))]
    for i, (m,n) in enumerate(matches):
        if m.distance < max_ratio * n.distance:
            match_mask[i] = [1, 0]
    
    plot_kwargs = {
        'matchColor': (0, 255, 0, 0.2),
        'singlePointColor': (255, 0, 0),
        'matchesMask': match_mask,
        'flags': cv.DrawMatchesFlags_DEFAULT
    }
    img_to_plot = cv.drawMatchesKnn(source, pts_src, target, pts_tgt, matches, None, **plot_kwargs)

    f, ax = plt.subplots(1, 1, figsize=(10, 10))
    ax.imshow(img_to_plot)
    ax.axis('off')
    ax.set_title('Matches')

    return f, ax

## SIFT Feature Extraction
Extraction of SIFT features for each image in the dataset